package:
    type:           project
    name:           hipanel
    title:          HiPanel
    headline:       Next generation control panel for
    keywords:       hipanel
    description:    |
        HiPanel is next generation control panel for hosting, domains and more.

        See [http://hipanel.com](http://hipanel.com).

vendor:
    name:           hipanel
